- hosts: all
  become: true
  tasks:
    - name: Copy war file from jenkins to tomcat
      archive:
        path: /opt/tomcat/webapps/webapp.war
        dest: /opt/tomcat/webapps/webapp_{{ansible_date_time.date}}.zip
        format: zip
