- hosts: all
  become: true
  tasks:
    - name: Delete old 10 days files from last 3 days
      shell:  find /home/ubuntu -mindepth 1 -mtime +10 -type f -delete
#####################################################################################################################
- hosts: all
  become: true
  tasks: 
    - name: deploy to tomcat
      copy:
        src: webapp/target/webapp.war
        dest: /opt/tomcat/webapps

