- hosts: all
  become: true
  tasks:
   - name: Log into DockerHub
     docker_login:
      username: mahendra96
      password: Mahendra@96
      email: annapureddymahendra@gmail.com
      
   - name: Pull image from docker hub
     command: docker pull mahendra96/sample:demo-"{{buildNumber}}"

   - name: Stop current running container
     command: docker stop phani-c1
     ignore_errors: yes

   - name: Remove stopped container
     command: docker rm phani-c1
     ignore_errors: yes

   - name: Run a container from the pulled image
     command: docker run -d --name container1 -p 80:8080 mahendra96/sample:demo-"{{buildNumber}}"
